# Generated by Django 2.2.3 on 2019-09-10 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videoteca', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='director',
            name='fecha_nacimiento',
        ),
    ]
