# Generated by Django 2.2.3 on 2023-12-27 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videoteca', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['-fecha'], 'verbose_name': 'Video', 'verbose_name_plural': 'Videos'},
        ),
    ]
