# Generated by Django 2.2.3 on 2024-07-03 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoteca', '0002_auto_20231226_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='director',
            name='nombre',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='episodio',
            name='slug',
            field=models.SlugField(editable=False, max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='episodio',
            name='titulo',
            field=models.CharField(max_length=225, unique=True, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='tipo',
            name='nombre',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='tipo',
            name='slug',
            field=models.SlugField(editable=False, max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='nombre',
            field=models.CharField(max_length=225, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='video',
            name='slug',
            field=models.SlugField(editable=False, max_length=250, unique=True),
        ),
    ]
