# Generated by Django 2.2.3 on 2024-07-03 04:25

from django.db import migrations, models

def transferir_tipo_a_tipos(apps, schema_editor):
    Videoteca = apps.get_model('videoteca', 'Video')
    for instancia in Videoteca.objects.all():
        instancia.temas.add(instancia.tipo)


class Migration(migrations.Migration):

    dependencies = [
        ('videoteca', '0003_auto_20240702_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='temas',
            field=models.ManyToManyField(related_name='temas', to='videoteca.Tipo', verbose_name='Temas'),
        ),
        migrations.RunPython(transferir_tipo_a_tipos),
    ]
