# Generated by Django 2.2.3 on 2019-10-07 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoteca', '0003_auto_20191007_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipo',
            name='slug',
            field=models.SlugField(default=1, editable=False, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='video',
            name='slug',
            field=models.SlugField(editable=False, max_length=250),
        ),
    ]
