# Generated by Django 2.2.3 on 2024-07-03 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videoteca', '0004_video_temas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='tipo',
        ),
    ]
