# Generated by Django 2.2.3 on 2024-07-03 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videoteca', '0005_remove_video_tipo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='temas',
            new_name='tipo',
        ),
    ]
