# Generated by Django 2.2.3 on 2024-08-08 02:12

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('videoteca', '0007_auto_20240708_2020'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipo',
            options={'ordering': ['-id'], 'verbose_name': 'Tema', 'verbose_name_plural': 'Temas'},
        ),
        migrations.AddField(
            model_name='tipo',
            name='portada',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='fotos/portadas', verbose_name='Portada'),
        ),
    ]
