# Generated by Django 2.2.3 on 2019-10-22 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programacion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horaprogramacion',
            name='categoria_p',
        ),
    ]
