# Generated by Django 2.2.3 on 2019-10-30 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programacion', '0002_remove_horaprogramacion_categoria_p'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horaprogramacion',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
    ]
