# Generated by Django 2.2.3 on 2023-12-27 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0002_biblioteca_categoria'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='biblioteca',
            options={'verbose_name': 'Biblioteca', 'verbose_name_plural': 'Bibliotecas'},
        ),
    ]
