# Generated by Django 2.2.3 on 2019-10-07 21:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields
import taggit_autosuggest.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lugar', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=225)),
                ('slug', models.SlugField(editable=False, max_length=250)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Comunicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.IntegerField(choices=[(1, 'Noticia'), (2, 'Reportaje')])),
                ('ultimo_momento', models.BooleanField(default=False)),
                ('portada', models.BooleanField(default=False, verbose_name='Portada')),
                ('titulo', models.CharField(max_length=225)),
                ('fecha', models.DateField()),
                ('banner', sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='banner/noticias', verbose_name='Banner')),
                ('foto', sorl.thumbnail.fields.ImageField(upload_to='fotos/noticias', verbose_name='Imagen')),
                ('descripcion', models.TextField()),
                ('fuente', models.CharField(max_length=225)),
                ('slug', models.SlugField(editable=False, max_length=250, unique=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noticias.Categoria')),
                ('pais', models.ForeignKey(on_delete=255, to='lugar.Pais')),
                ('tags', taggit_autosuggest.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Noticia/Reportaje',
                'verbose_name_plural': 'Noticias/Reportajes',
            },
        ),
    ]
