# Generated by Django 2.2.3 on 2019-10-07 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0003_auto_20190910_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='slug',
            field=models.SlugField(default=1, editable=False, max_length=250),
            preserve_default=False,
        ),
    ]
