# Generated by Django 2.2.3 on 2024-07-03 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizacion',
            name='nombre',
            field=models.CharField(max_length=200, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='organizacion',
            name='slug',
            field=models.SlugField(editable=False, max_length=200, unique=True),
        ),
    ]
