# Generated by Django 2.2.3 on 2024-07-03 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lugar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pais',
            name='slug',
            field=models.SlugField(default='nada', max_length=225),
            preserve_default=False,
        ),
    ]
