# Generated by Django 2.2.3 on 2024-07-03 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lugar', '0002_pais_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pais',
            name='slug',
            field=models.SlugField(editable=False, max_length=225, unique=True),
        ),
    ]
