# Generated by Django 2.2.3 on 2024-07-03 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lugar', '0003_auto_20240702_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pais',
            name='nombre',
            field=models.CharField(max_length=225, unique=True),
        ),
        migrations.AlterField(
            model_name='pais',
            name='slug',
            field=models.SlugField(max_length=225, unique=True),
        ),
    ]
