# Generated by Django 2.2.3 on 2019-10-29 16:59

from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConocenosImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', sorl.thumbnail.fields.ImageField(upload_to='banner/conocenos')),
            ],
            options={
                'verbose_name': 'Imagen conocenos',
            },
        ),
    ]
