# Generated by Django 2.2.3 on 2019-10-29 17:10

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conocenosimg',
            options={'verbose_name': 'Imágen conócenos'},
        ),
        migrations.AlterField(
            model_name='conocenosimg',
            name='imagen',
            field=sorl.thumbnail.fields.ImageField(blank=True, help_text='1350x280', null=True, upload_to='banner/conocenos'),
        ),
    ]
