# Generated by Django 2.2.3 on 2023-12-27 03:23

from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0003_bannersitio_inlinesimages'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoticiaImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', sorl.thumbnail.fields.ImageField(blank=True, help_text='1350x280', null=True, upload_to='banner/conocenos')),
            ],
            options={
                'verbose_name': 'Imágen de noticias',
            },
        ),
    ]
